version: '3.7'
networks:
  lip-net:
    driver: bridge
services:
  lip:
    image: iudx/lip-dev:latest
    volumes:
      - ./secrets/all-verticles-configs/config-dev.json:/usr/share/app/secrets/all-verticles-configs/config.json
    networks: 
      - lip-net
